#!/usr/bin/env bash
# install and configure HAproxy

sudo apt-get update
sudo apt-get install haproxy=1.6.\*

sudo echo "frontend LOADBALANCER-01
    bind  *:80
    default_backend WEBSERVERS-01" >> /etc/haproxy/haproxy.cfg

sudo echo 'backend WEBSERVERS-01
    balance roundrobin
    server 1894-web-01 35.227.48.225:80 check
    server 1894-web-02 34.74.219.148:80 check' >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
