#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times

i=0
while [ $i -lt 10 ];
do
    echo "Holberton School"
    if [ $i -eq 3 ]; then
        echo "bad luck"
    elif [ $i -eq 7 ]; then
        echo "good luck"
    fi
    let i=i+1
done