#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times

i=1
count=1
echo "Hour: 0"
while [ $i -le 59 ];
do
    echo "$i"
    if [ $count -eq 13 ] && [ $i == 59 ]; then
        break
    fi
    case $i in
    59)
        let i=1
        echo "Hour: $count"
        let count=count+1
        echo "$i"
    esac
    let i=i+1
done